config/routes.rb
Rails.application.routes.draw do
  
  get 'user/display'
  get 'profile/liked'
  get 'profile/reviewed'
  devise_for :users
  resources :meals do
  	#search will apply to more than one restaurant
  	collection do
      get 'search'
    end
  	resources :reviews, except: [:show, :index]
  end
  
  get 'pages/about'

  get 'pages/contact'

  root 'meals#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get 'users/:id/reviews' => 'users#reviews', :as => :user_reviews
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
	mount_uploader :avatar, AvatarUploader

	searchkick


  	has_many :reviews
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	
end

app/models/review.rb
class Review < ApplicationRecord
	belongs_to :user
  	belongs_to :meal
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reviews, dependent: :destroy 

 def reviews
    @user = User.find(params[:id])
    @reviews = @user.reviews
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base




end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  before_action :set_meal, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:search, :index, :show]
  


  def search
    if params[:search].present?
     @meals = Meal.search(params[:search])
    else
     @meals = Meal.all
    end
  end


  # GET /meals or /meals.json
  def index
    @meals = Meal.all
  end

  # GET /meals/1 or /meals/1.json
  def show
    @reviews = Review.where(meal_id: @meal.id)
  end

  # GET /meals/new
  def new
    @meal = Meal.new
  end

  # GET /meals/1/edit
  def edit
  end

  # POST /meals or /meals.json
  def create
    @meal = Meal.new(meal_params)

    respond_to do |format|
      if @meal.save
        format.html { redirect_to @meal, notice: "Meal was successfully created." }
        format.json { render :show, status: :created, location: @meal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meals/1 or /meals/1.json
  def update
    respond_to do |format|
      if @meal.update(meal_params)
        format.html { redirect_to @meal, notice: "Meal was successfully updated." }
        format.json { render :show, status: :ok, location: @meal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @meal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meals/1 or /meals/1.json
  def destroy
    @meal.destroy
    respond_to do |format|
      format.html { redirect_to meals_url, notice: "Meal was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meal
      @meal = Meal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def meal_params
      params.require(:meal).permit(:day_time, :item1, :item2, :item3, :item4, :avatar)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def liked
  end

  def reviewed
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[ show edit update destroy ]

  # GET /restaurants or /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1 or /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants or /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: "Restaurant was successfully created." }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1 or /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: "Restaurant was successfully updated." }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1 or /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: "Restaurant was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :address, :phone, :website)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ edit update destroy ]
  before_action :set_meal
  before_action :authenticate_user!

  # GET /reviews/new
  def new
    @review = Review.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.meal_id = @meal.id

    respond_to do |format|
      if @review.save
        format.html { redirect_to meal_path(@meal), notice: "Review was successfully created." }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    def set_meal
      @meal = Meal.find(params[:meal_id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

 
  def reviews
    @user = User.find(params[@id])
    @reviews = @user.reviews
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_bootstrap.html.erb
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
 
 <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

app/views/layouts/_footer.html.erb
<p>Copyright Gabriela Carretero</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg sticky-top navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"> TIGER EATS </a>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item"><a class="nav-link" href="/pages/contact">Contact Us</a></li>
      </ul>

      <ul class="navbar-nav">
        <% if user_signed_in? %>
          <li class="nav-item"><a class="nav-link" href="/users/edit"> Edit Profile</a></li>
          <li class="nav-item"><a class="nav-link" href="users/:id/reviews"> Meals Reviewed</a></li>
          <li class="nav-item"><a class="nav-link" data-method="delete" href="<%= destroy_user_session_path %>">
            <i class="fa fa-sign-out" aria-hidden="true"></i><span class="hidden-xs hidden-sm"> Sign Out</span>
          </a></li>
           <!--li class="nav-item"><a class="nav-link" href="/profile/liked"> Liked Meals</a></li-->
           <!--%= link_to review.user.name, user_review_path(post.user) %-->
          
          <!-- Put personal page here -->
        <% else %>
          <li class="nav-item"><a class="nav-link" href="/users/sign_up"> Sign Up</a></li>
          <li class="nav-item"><a class="nav-link" href="/users/sign_in"> Sign In</a></li>
        <% end %>
      </ul>
      <br><br>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TIGER EATS</title>
    <%= render 'layouts/bootstrap' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
   
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class= "container-fluid">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/meals/_form.html.erb
<%= form_with(model: meal, :html => { multipart: true }) do |form| %>
  <% if meal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meal.errors.count, "error") %> prohibited this meal from being saved:</h2>

      <ul>
        <% meal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :day_time %>
    <%= form.text_field :day_time, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :item1 %>
    <%= form.text_field :item1, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :item2 %>
    <%= form.text_field :item2, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :item3 %>
    <%= form.text_field :item3, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :item4 %>
    <%= form.text_field :item4, class: "form-control" %>
  </div>

   <div class="form-group">
    <%= form.label :avatar %>
    <%= form.file_field :avatar, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-outline-warning" %>
  </div>
<% end %>

app/views/meals/edit.html.erb
<h1>Editing Meal</h1>

<%= render 'form', meal: @meal %>

<%= link_to 'Show', @meal, class: "btn btn-link" %> |
<%= link_to 'Back', meals_path, class: "btn btn-link" %>

app/views/meals/index.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container">
    <h1 class="display-4">Welcome to Tiger Eats!</h1>
    <h3 class="lead"> Check out this weeks menu & leave reviews and ratings for your your fellow foodies!</h3>
  </div>
</div>

<p id="notice"><%= notice %></p>


      <%= form_tag search_meals_path, method: :get, class: "navbar-form navbar-left" do %>
      <p>
      <%= text_field_tag :search, params[:search], class: "form-control" %>
      <%= submit_tag  "Search", name: nil, class: "btn btn-default" %>
      </p>
      <% end %>

<h1>Meals</h1>

<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Day time</th>
      <th>Item1</th>
      <th>Item2</th>
      <th>Item3</th>
      <th>Item4</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @meals.each do |meal| %>
      <tr>
        <td><%= meal.day_time %></td>
        <td><%= meal.item1 %></td>
        <td><%= meal.item2 %></td>
        <td><%= meal.item3 %></td>
        <td><%= meal.item4 %></td>
        <td><%= link_to 'Show', meal, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_meal_path(meal), class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Meal', new_meal_path, class: "btn btn-link" %>

app/views/meals/new.html.erb
<h1>Add a New Meal</h1>

<%= render 'form', meal: @meal %>

<%= link_to 'Back', meals_path, class: "btn btn-link" %>

app/views/meals/search.html.erb
<table class="table table-hover table-condensed">
  <thead>
    <tr>
      <th>Day time</th>
      <th>Item1</th>
      <th>Item2</th>
      <th>Item3</th>
      <th>Item4</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @meals.each do |meal| %>
      <tr>
        <td><%= meal.day_time %></td>
        <td><%= meal.item1 %></td>
        <td><%= meal.item2 %></td>
        <td><%= meal.item3 %></td>
        <td><%= meal.item4 %></td>
        <td><%= link_to 'Show', meal, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_meal_path(meal), class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', meal, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/meals/show.html.erb
<div class="row">
  <div class="col-md-3">
    <%= image_tag @meal.avatar_url, class: "img-thumbnail" %>
    <h2>
      <%= @meal.day_time %>
    </h2>
    <br>
    <h4>
      <%= @meal.item1 %>
    </h4>
    <br>
    <h4>
      <%= @meal.item2 %>
    </h4>
    <br>
    <h4>
      <%= @meal.item3 %>
    </h4>
    <br>
    <h4>
      <%= @meal.item4 %>
    </h4>
    <br>
    <br>
    <%= link_to "Write Review", new_meal_review_path(@meal), class: "btn btn-primary" %>
  </div>

  <div class="col-md-9">
    <% if @reviews.blank? %>
    <h3> This item does not have any reviews yet. Be the first to write one! </h3>
    <% else %>
      <% @reviews.each do |review| %>
        <p><%= review.rating %></p>
        <p><%= review.comment %></p>
      <% end %>
    <% end %>
  </div>
</div>

<%= link_to 'Edit', edit_meal_path(@meal), class: "btn btn-link" %> |
<%= link_to 'Back', meals_path, class: "btn btn-link" %>

app/views/pages/about.html.erb
<h1>Welcome to Tiger Eats!</h1>
<h2>This is an application for my senior seminar, a project that must be completed in order to graduate with a Computer Science Seminar. I am using Ruby on Rails programming language. This application uses information provided by DePauw's <a href="https://depauw.cafebonappetit.com/">Hoover Dining Hall</a>. Enjoy!</h2>

app/views/pages/contact.html.erb
<h1>We would love to hear from you!</h1>

<html>
<body>


<form action="mailto:admin@tigereats.com" method="post" enctype="text/plain">
 <br>Have suggestions on how we can improve? Let us know!<br> 
<input type="text" name="comment" size="50"><br><br>
<input type="submit" value="Send">
<input type="reset" value="Reset">
<br><br>
</form>

</body>
</html>
<!-- Simple HTML Form that “Triggers” an Email.-->

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
        <% restaurant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :website %>
    <%= form.text_field :website %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1>Editing Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Show', @restaurant %> |
<%= link_to 'Back', restaurants_path %>

app/views/restaurants/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurants</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone %></td>
        <td><%= restaurant.website %></td>
        <td><%= link_to 'Show', restaurant %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
        <td><%= link_to 'Destroy', restaurant, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= render 'form', restaurant: @restaurant %>

<%= link_to 'Back', restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @restaurant.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @restaurant.phone %>
</p>

<p>
  <strong>Website:</strong>
  <%= @restaurant.website %>
</p>

<%= link_to 'Edit', edit_restaurant_path(@restaurant) %> |
<%= link_to 'Back', restaurants_path %>

app/views/reviews/_form.html.erb
<%= form_for([@meal, @review]) do |form| %>
  <% if review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
        <% review.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :rating %>
    <%= form.number_field :rating, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :comment %>
    <%= form.text_area :comment, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', meal_path(@meal) %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Back', meal_path(@meal) %>

app/views/user/display.html.erb
<h1>User#display</h1>
<p>Find me in app/views/user/display.html.erb</p>